### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by bertzzie** [bliblidotcom/java-common-helper#1]
We need some docs for people who wanted to adopt this library. Some basic preliminaries:

- [x] `readme.md`
- [x] Wiki pages showing example usages and when to use it
- [x] Generated javadoc in separate [github page](https://pages.github.com/).

Anyone who's interested in contributing please add those stuffs to different PRs for easier management.

**Comment by bunthatcodes** [comment]
@bertzzie please review the [wiki page](https://github.com/bliblidotcom/java-common-helper/wiki) and [javadoc page](https://bliblidotcom.github.io/java-common-helper/).
