### ISSUE TITLE
Utilize Stream API on CollectionHelper

### ISSUE THREAD

**Issue by bertzzie** [bliblidotcom/java-common-helper#2]
Right now we have mixes of:

- iterators,
- foreach loop, and
- Stream API

for handling collections in `CollectionHelper`. It would be better to use the same method (either one is fine) for all of the methods. Let's simplify and standardize it. I suggest Stream API and then just declare java 8 only support.

This is open to discussion.

**Comment by bunthatcodes** [comment]
I have modified most of the helpers to use Stream API as of 0.0.11
