### ISSUE TITLE
add continuous integration with codacy

### ISSUE THREAD

**Issue by andirdju** [bliblidotcom/java-common-helper#6]
https://app.codacy.com/app/bliblidotcom

example:
- https://github.com/bliblidotcom/command-plugin/pull/9

**Comment by bunthatcodes** [comment]
@andirdju please check
https://app.codacy.com/app/bunthatcodes/java-common-helper/dashboard

**Comment by andirdju** [comment]
lets move it here
https://app.codacy.com/app/projectList/bliblidotcom/java-common-helper

and accept the invite that I sent from our codacy account
